---
engine: knitr

---

# Introduction

## Before beginning

::: {.callout-tip appearance="simple"}
## Attention!

Please open [this link](https://mybinder.org/v2/gh/CBFLivUni/scholars_event/HEAD?urlpath=%2Fdoc%2Ftree%2Findex.ipynb) **in a new tab** and let it load, this may take a few minutes.
:::

This is a short programming activity to teach you how to create plots using Python, in a real-life programming environment known as a **Jupyter notebook**. The session should run 60-90 minutes total. 

## General guidance and tips

-   Take your time and read all the instructions on this page and the following pages - if you skip forward you may miss *important information that can help you later*
-   To copy code more easily you can highlight it and press 'ctrl' + 'c' on your keyboard at the same time
-   To paste code you can use the keyboard shortcut 'ctrl' + 'v'


## Running the code

For much of this activity you will be copying blocks of code from the instructions and pasting them into the Jupyter notebook. An example of what a code block looks like below. You can copy the code either by highlighting it and copying OR if you hover over the block a little clipboard symbol will appear to the right. If you click it it will copy the code. Try and copy the example block below.


```{python}

print("I am a Python code block.")

```